---
#
# find first valid ucp server
#
#   sets ucp_instance to the name of the first instance found
#   sets ucp_instance to ".none." if no instance was found
#


- name: init
  uri:
    url: "https://{{ groups.ucp[0] }}.{{ domain_name }}/_thereisnosuchpage"
    headers:
      Content-Type: application/json
    method: POST
    status_code: 200,500
    validate_certs: no
  delegate_to: localhost
  register: checks
  failed_when: false
  changed_when: false

- name: check
  uri:
    url: "https://{{ item }}.{{ domain_name }}/auth/login"
    headers:
      Content-Type: application/json
    method: POST
    status_code: 200,500
    body_format: json
    validate_certs: no
    body: '{"username":"{{ ucp_username }}","password":"{{ ucp_password }}"}'
  delegate_to: localhost
  register: checks
  failed_when: false
  changed_when: false
  when: checks.status !=200 and checks.status != 500 
  with_items: "{{ ping_servers }}"


- set_fact: ucp_instance=".none."
- name: set ucp_instance
  set_fact: ucp_instance={{ item.item }}
  when: "'status' in item and item.status == 200"
  with_items: "{{ checks.results }}"

