    - name: Retrieve a token for the SimpliVity API
      uri:
        url: "https://simplivity@{{ ovc }}/api/oauth/token"
        headers:
          Content-Type: application/x-www-form-urlencoded
        method: POST
        status_code: 200
        body: 'grant_type=password&username={{ simplivity_username }}&password={{ simplivity_password}}' 
        force_basic_auth: yes
        validate_certs: no
        use_proxy: no
      register: login
      until: login.status == 200
      retries: 3
      delay: 5

    - debug:
        var: login.json.access_token
      when: _debug is defined

    - set_fact:
        svt_token: "{{ login.json.access_token }}"
